chore: add to_list function for value
aiken-lang/stdlib pull request #31
Opened 2023-04-30 21:23 UTC by MicroProofs

The why:

Sometimes you may just want access to the list of values to work directly with list destructuring. i.e. using expect or when

I consider this a more advanced usage, but there is quite the case for the cost savings. Like iterating over a larger amount of outputs. Calling tokens or flatten is not efficient enough once your outputs list reaches a large enough size. So in this case I wanted to add an escape hatch to work directly with the "List" of values.

2023-05-01 00:31 UTC, rvcas approved these changes

2023-05-01 07:25 UTC, KtorZ requested changes
We should keep consistency with other functions like flatten with regards to null values. It'd be odd that flatten returns a list and to list return another slightly different.

2023-05-01 15:20 UTC, MicroProofs commented
> We should keep consistency with other functions like flatten with regards to null values. It'd be odd that flatten returns a list and to list return another slightly different. 
> 
> 

Not sure what you mean? I could change the name. But the function shouldn't do more than what it currently does since it is currently zero cost to call.

2023-05-02 06:21 UTC, KtorZ commented
@MicroProofs at the moment, we enforce a few invariants in the API of this module; in particular: we do not return 0-quantity assets. The typical case is when transactions include a 0-quantity of Ada tokens in the `mint` field (which [might be fixed in Plutus V3](https://github.com/input-output-hk/plutus/issues/5039#issuecomment-1491966873)). 

Now, calling `flatten` gets rid of this extra null value; and we should preserve this behavior across all functions from this API. So `to_list` or `to_dict` shall also filter out this value. We can't really have a zero cost function in there because of this.

2023-05-02 15:16 UTC, rvcas commented
@KtorZ I don't understand a module can have any API, there's no reason to maintain the uniformity you describe that seems artificial. Doing this is just much cheaper than the current functions. What other alternative is there?

2023-05-02 15:43 UTC, KtorZ commented
Of course, but wouldn't you be surprised if calling `flatten` yields you 1 elements whereas calling `to_list` yields you two, one missing from `flatten`? Of course you can mention it in the documentation and so on, but that's still very surprising. 

Another weird thing is that I'd imagine this to be idempotent. But now, if I have a value, call `to_list`, then turn that list back into a `Value`, and call `to_list` again, the zero-quantity assets will have disappeared from the second `to_list`. That is also a highly surprising behavior. 

So, we either don't do anything about zero-quantity assets at all, or we do it consistently everywhere. From now-months-old conversations on Discord, we did settle about abstracting away those zero values. I am still not 100% convinced that this is the right call, because it creates other surprising behaviors such as unexpected `==` outcomes. 

I am thinking that it's perhaps just best to keep those zero-quantity assets and simply compose with them. Let people know that they are a thing, and let people strip away with functions like `flatten_with` if they want to. That would more faithfully represent the actual data that is on-chain; and it also makes everything else cheaper as we can get rid of all the null checks.

--- 

From a purely aesthetic point of view, I also find it weird to return a list of tuples, and not a `dict`. So I'd rather consider a `to_dict` function, irrespective of the other conversation.

2023-05-02 15:49 UTC, KtorZ commented
Okay I have a concrete proposal now that can perhaps settle it. I just realized that from writing my previous comment. 
What about we define two types? `Value` and `MintedTokens` (whatever the name is). 

And simply provide some methods for working with `MintedTokens`, or even just a `to_value` conversion which takes care of efficiently removing the zero-quantity lovelace from there. So the extra cost is only paid once, and only for mint values.

2023-05-02 16:03 UTC, MicroProofs commented
I think the whole point of this was to add advanced functions that are not generally used by anyone except people who really know what they are doing. I planned to keep the whole advanced usage in there and not have this as a function that is used by most people because it has a different result than normal.

2023-05-02 16:07 UTC, MicroProofs commented
> Okay I have a concrete proposal now that can perhaps settle it. I just realized that from writing my previous comment. 
> 
> What about we define two types? `Value` and `MintedTokens` (whatever the name is). 
> 
> 
> 
> And simply provide some methods for working with `MintedTokens`, or even just a `to_value` conversion which takes care of efficiently removing the zero-quantity lovelace from there. So the extra cost is only paid once, and only for mint values. 
> 
> 
> 
> 

Hmmm I guess this is acceptable. Would MintedTokens still have the same tokens(policy) function?

2023-05-02 16:33 UTC, rvcas commented
@KtorZ clever idea

2023-06-04 20:17 UTC, closed without merging